import LegalPage, { type LegalSection } from "@/components/legal/LegalPage";
import { getContactContent } from "@/lib/database/contact";
import { getSiteSettings } from "@/lib/database/settings";
import { getRequestLocale } from "@/lib/i18n/server";
import { createPageMetadata } from "@/lib/seo";

export async function generateMetadata() {
  const locale = await getRequestLocale();
  return createPageMetadata({
    path: "/terms",
    title: locale === "it" ? "Termini e condizioni | Movento" : "Terms and Conditions | Movento",
    description: locale === "it"
      ? "Termini per l’uso del sito Movento, richieste di preventivo, prenotazioni e servizi di trasloco."
      : "Terms governing the Movento website, quote requests, bookings and moving services.",
  });
}

export default async function TermsPage() {
  const locale = await getRequestLocale();
  const [settings, contact] = await Promise.all([getSiteSettings(), getContactContent(locale)]);
  const businessName = settings?.publicTradingName?.trim() || "Movento";
  const address = contact?.address?.trim();
  const it = locale === "it";

  const sections: LegalSection[] = it ? [
    { title: "1. Ambito di applicazione", paragraphs: [`Questi termini regolano l’uso del sito ${businessName}, le richieste di preventivo e gli eventuali servizi di trasloco, trasporto, imballaggio, montaggio, deposito o assistenza concordati con il cliente. Il sito fornisce informazioni e strumenti di richiesta; l’invio di un modulo non costituisce automaticamente un contratto.`] },
    { title: "2. Preventivi e conferma del servizio", paragraphs: ["Le stime online sono indicative e dipendono dalle informazioni fornite. Il prezzo definitivo, l’ambito del servizio, la data, il personale e gli eventuali costi aggiuntivi sono validi solo quando confermati per iscritto da Movento.", "Il cliente deve comunicare informazioni complete su volume, piani, ascensori, accessi, parcheggio, distanze di trasporto, oggetti pesanti o fragili e servizi richiesti. Informazioni mancanti o inesatte possono comportare modifiche al prezzo o al programma."] },
    { title: "3. Prenotazioni, modifiche e cancellazioni", paragraphs: ["Una data è riservata solo dopo conferma scritta ed eventuale pagamento concordato. Le richieste di modifica o cancellazione devono essere inviate il prima possibile.", "Eventuali costi di cancellazione, riprogrammazione, attesa o viaggio saranno comunicati prima della conferma quando applicabili. Movento può riprogrammare per motivi di sicurezza, indisponibilità imprevedibile, condizioni stradali o eventi fuori dal proprio ragionevole controllo."] },
    { title: "4. Responsabilità del cliente e accesso", paragraphs: ["Il cliente deve assicurare un accesso legale e sicuro agli immobili, ottenere permessi condominiali o di parcheggio necessari, proteggere pavimenti o aree non incluse nel servizio e garantire che una persona autorizzata sia disponibile.", "Il cliente deve scollegare apparecchi, svuotare e preparare gli oggetti come concordato, salvo che tali attività siano incluse nel servizio. Ritardi, accessi non dichiarati o condizioni pericolose possono richiedere un nuovo accordo."] },
    { title: "5. Oggetti esclusi o soggetti a condizioni", paragraphs: ["Salvo accordo scritto, non devono essere consegnati sostanze illegali o pericolose, esplosivi, carburanti, armi, animali, piante soggette a restrizioni, alimenti deperibili, denaro, titoli, gioielli, documenti essenziali o oggetti di valore eccezionale.", "Il cliente deve segnalare in anticipo pianoforti, casseforti, opere d’arte, vetri, elettrodomestici pesanti o oggetti che richiedono attrezzature o competenze speciali."] },
    { title: "6. Pagamenti", paragraphs: ["Importi, scadenze, acconti e metodi di pagamento sono indicati nel preventivo o nell’accordo scritto. I servizi aggiuntivi richiesti o resi necessari il giorno del trasloco possono essere fatturati separatamente previa informazione al cliente.", "Il cliente è responsabile degli importi dovuti secondo l’accordo confermato e delle spese documentate autorizzate, come permessi, pedaggi o servizi di terzi."] },
    { title: "7. Danni e segnalazioni", paragraphs: ["Movento opera con cura professionale. Il cliente deve controllare i beni alla consegna e segnalare per iscritto eventuali perdite o danni senza ritardo, allegando descrizione, fotografie e prova del valore quando disponibile.", "La responsabilità sarà valutata secondo il servizio concordato, le circostanze, la legge applicabile e ogni copertura assicurativa comunicata. Movento non risponde del normale deterioramento, di difetti preesistenti, imballaggio effettuato dal cliente in modo inadeguato o conseguenze di informazioni omesse."] },
    { title: "8. Terzi, sito e proprietà intellettuale", paragraphs: ["Movento può utilizzare fornitori o collegamenti di terzi per mappe, comunicazioni, pagamenti o servizi specialistici. Le condizioni del terzo possono applicarsi separatamente.", "I contenuti del sito, il marchio, la grafica e i testi non possono essere copiati o utilizzati in modo ingannevole. È vietato interferire con la sicurezza del sito, inviare contenuti illeciti o utilizzare i moduli per spam o frode."] },
    { title: "9. Legge applicabile, reclami e contatti", paragraphs: [`I rapporti con i consumatori sono regolati dalla legge italiana e dalle tutele inderogabili applicabili nell’Unione europea. Per reclami o domande: info@moventoitalia.com${address ? ` oppure ${address}` : ""}. Eventuali controversie saranno trattate dall’autorità competente secondo la legge applicabile.`] },
  ] : [
    { title: "1. Scope", paragraphs: [`These terms govern use of the ${businessName} website, quote requests and any moving, transport, packing, assembly, storage or support services agreed with a customer. The website provides information and enquiry tools; submitting a form does not automatically create a contract.`] },
    { title: "2. Quotes and service confirmation", paragraphs: ["Online estimates are indicative and depend on the information supplied. The final price, service scope, date, staffing and any additional costs become binding only when confirmed in writing by Movento.", "Customers must provide complete information about volume, floors, lifts, access, parking, carrying distances, heavy or fragile items and required services. Missing or inaccurate details may require price or schedule changes."] },
    { title: "3. Bookings, changes and cancellations", paragraphs: ["A date is reserved only after written confirmation and any agreed payment. Change or cancellation requests must be made as early as possible.", "Applicable cancellation, rescheduling, waiting or travel charges will be disclosed before confirmation where relevant. Movento may reschedule for safety, unforeseen unavailability, road conditions or events outside its reasonable control."] },
    { title: "4. Customer responsibilities and access", paragraphs: ["The customer must provide lawful and safe property access, obtain necessary building or parking permissions, protect areas outside the agreed work and ensure an authorised person is available.", "Appliances must be disconnected and belongings prepared as agreed unless those tasks are included. Undisclosed access restrictions, delays or unsafe conditions may require a revised agreement."] },
    { title: "5. Prohibited and special items", paragraphs: ["Unless agreed in writing, customers must not provide illegal or dangerous substances, explosives, fuel, weapons, animals, restricted plants, perishables, cash, securities, jewellery, essential documents or exceptionally valuable items.", "Pianos, safes, artwork, glass, heavy appliances and anything requiring specialist equipment must be disclosed before confirmation."] },
    { title: "6. Payments", paragraphs: ["Prices, due dates, deposits and payment methods are stated in the written quote or agreement. Additional work requested or reasonably required on moving day may be charged separately after the customer is informed.", "The customer remains responsible for confirmed charges and authorised documented costs such as permits, tolls or third-party services."] },
    { title: "7. Damage and reporting", paragraphs: ["Movento performs services with professional care. Customers should inspect belongings on delivery and report suspected loss or damage promptly in writing, with a description, photographs and evidence of value where available.", "Responsibility is assessed according to the agreed service, circumstances, applicable law and any disclosed insurance cover. Movento is not responsible for ordinary wear, pre-existing defects, inadequate customer packing or consequences of omitted information."] },
    { title: "8. Third parties, website use and intellectual property", paragraphs: ["Movento may use third-party providers for maps, communications, payments or specialist services. Separate third-party terms may apply.", "Website content, branding, graphics and text must not be copied or used misleadingly. Users must not interfere with security, submit unlawful material, or use forms for spam or fraud."] },
    { title: "9. Governing law, complaints and contact", paragraphs: [`Consumer relationships are governed by Italian law and applicable mandatory EU consumer protections. Questions or complaints may be sent to info@moventoitalia.com${address ? ` or ${address}` : ""}. Disputes are handled by the competent authority under applicable law.`] },
  ];

  return <LegalPage path="/terms" locale={locale} eyebrow={it ? "Informazioni legali" : "Legal information"} title={it ? "Termini e condizioni" : "Terms and Conditions"} introduction={it ? "Condizioni principali per utilizzare il sito e richiedere o acquistare servizi Movento." : "The principal conditions for using this website and requesting or purchasing Movento services."} updatedLabel={it ? "Ultimo aggiornamento: 28 luglio 2026" : "Last updated: 28 July 2026"} sections={sections} reviewNotice={it ? "Avviso: questo testo costituisce una base informativa operativa e deve essere sottoposto a revisione professionale/legale finale prima dell’avvio delle attività commerciali." : "Notice: this text is an operational information baseline and should receive final professional/legal review before commercial operations begin."} />;
}
