"use client";
import Image from "next/image";
import { useActionState } from "react";
import { Save } from "lucide-react";
import { saveSiteChrome } from "@/app/admin/(protected)/navigation/actions";
import type { ContactContent } from "@/lib/database/contact";
import type { SiteChrome } from "@/lib/database/site-chrome";
const input="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 outline-none transition focus:border-blue-600 focus:ring-4 focus:ring-blue-100";
export default function SiteChromeEditorForm({chrome,contact}:{chrome:SiteChrome;contact:ContactContent}){const[state,action,pending]=useActionState(saveSiteChrome,undefined);const navigation=chrome.navigation.map(item=>`${item.label}|${item.href}|${item.visible?"visible":"hidden"}`).join("\n");const navigationIt=chrome.navigation.map(item=>`${item.labelIt??""}|${item.href}`).join("\n");const footerNavigation=chrome.footerNavigation.flatMap(group=>group.links.map(link=>`${group.title}|${link.label}|${link.href}`)).join("\n");const footerNavigationIt=chrome.footerNavigation.flatMap(group=>group.links.map(link=>`${group.titleIt??""}|${link.labelIt??""}|${link.href}`)).join("\n");const socials=chrome.socialLinks.map(link=>`${link.label}|${link.href}`).join("\n");return <form action={action} className="mt-8 space-y-6">
  <Section title="Header"><div className="flex items-center gap-5"><Image src={chrome.companyLogo} alt={chrome.companyName} width={1716} height={889} className="h-20 w-auto"/><p className="text-sm text-slate-500">The supplied transparent Movento logo remains unboxed.</p></div><div className="grid gap-5 sm:grid-cols-2"><Field name="companyName" label="Company name" value={chrome.companyName}/><Field name="companyLogo" label="Company logo path" value={chrome.companyLogo}/><Field name="headerCtaLabel" label="Header CTA text" value={chrome.headerCta.label}/><Field name="headerCtaLabelIt" label="Header CTA — Italiano" value={chrome.headerCta.labelIt} required={false}/><Field name="headerCtaHref" label="Header CTA link" value={chrome.headerCta.href}/></div><Area name="navigation" label="Navigation items" value={navigation} help="One per line: Label | /link | visible or hidden." rows={8}/><Area name="navigationIt" label="Navigazione — Italiano" value={navigationIt} help="Una per riga: Etichetta | /link" rows={8}/></Section>
  <Section title="Footer branding"><div className="grid gap-5 sm:grid-cols-2"><Field name="footerLogo" label="Footer logo path" value={chrome.footerLogo}/><Field name="footerTagline" label="Footer tagline" value={chrome.footerTagline}/><Field name="footerTaglineIt" label="Footer tagline — Italiano" value={chrome.footerTaglineIt} required={false}/></div><Area name="footerDescription" label="Footer description" value={chrome.footerDescription}/><Area name="footerDescriptionIt" label="Descrizione footer — Italiano" value={chrome.footerDescriptionIt}/><Area name="socialLinks" label="Social media links" value={socials} help="One per line: Label | https://example.com"/><Area name="footerNavigation" label="Footer navigation links" value={footerNavigation} help="One per line: Group title | Link label | /link" rows={9}/><Area name="footerNavigationIt" label="Navigazione footer — Italiano" value={footerNavigationIt} help="Una per riga: Titolo gruppo | Etichetta | /link" rows={9}/><Field name="copyrightText" label="Copyright text" value={chrome.copyrightText}/><Field name="copyrightTextIt" label="Copyright — Italiano" value={chrome.copyrightTextIt} required={false}/></Section>
  <Section title="Footer call to action"><div className="grid gap-5 sm:grid-cols-2"><Field name="footerCtaTitle" label="Title" value={chrome.footerCta.title}/><Field name="footerCtaTitleIt" label="Titolo — Italiano" value={chrome.footerCta.titleIt} required={false}/><Field name="footerCtaButtonLabel" label="Button text" value={chrome.footerCta.buttonLabel}/><Field name="footerCtaButtonLabelIt" label="Pulsante — Italiano" value={chrome.footerCta.buttonLabelIt} required={false}/><Field name="footerCtaButtonHref" label="Button link" value={chrome.footerCta.buttonHref}/></div><Area name="footerCtaDescription" label="Description" value={chrome.footerCta.description}/><Area name="footerCtaDescriptionIt" label="Descrizione — Italiano" value={chrome.footerCta.descriptionIt}/></Section>
  <Section title="Shared contact information"><p className="text-sm text-slate-500">These fields update the same Contact document used by the Contact Editor.</p><div className="grid gap-5 sm:grid-cols-2"><Field name="address" label="Address" value={contact.address}/><Field name="addressIt" label="Indirizzo — Italiano" value={contact.addressIt} required={false}/><Field name="phone" label="Phone" value={contact.phone}/><Field name="email" label="Email" value={contact.email} type="email"/><Field name="whatsapp" label="WhatsApp" value={contact.whatsapp}/></div><Area name="callingHours" label="Calling hours" value={contact.callingHours}/></Section>
  <div className="sticky bottom-5 flex items-center gap-4 rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-xl">{state&&<p className={`text-sm font-bold ${state.status==="success"?"text-emerald-700":"text-red-700"}`}>{state.message}</p>}<button disabled={pending} className="ml-auto inline-flex items-center gap-2 rounded-xl bg-blue-700 px-6 py-3 font-bold text-white disabled:opacity-60"><Save className="h-4 w-4"/>{pending?"Saving…":"Save header & footer"}</button></div>
</form>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="grid gap-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-extrabold">{title}</h2>{children}</section>}function Field({name,label,value,required=true,...props}:{name:string;label:string;value:string;required?:boolean;type?:string}){return <label><span className="text-sm font-bold">{label}</span><input name={name} defaultValue={value} required={required} className={input} {...props}/></label>}function Area({name,label,value,help,rows=4}:{name:string;label:string;value:string;help?:string;rows?:number}){return <label><span className="text-sm font-bold">{label}</span>{help&&<span className="mt-1 block text-xs text-slate-500">{help}</span>}<textarea name={name} defaultValue={value} rows={rows} className={`${input} resize-y`}/></label>}
