"use server";
import { FieldValue } from "firebase-admin/firestore";
import { revalidatePath, revalidateTag } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/session";
import { adminDb } from "@/lib/database/firebase-admin";
import { CONTACT_COLLECTION,CONTACT_DOCUMENT } from "@/lib/database/contact";
import { SITE_CHROME_COLLECTION,SITE_CHROME_DOCUMENT } from "@/lib/database/site-chrome";

const internalPath=z.string().trim().regex(/^\/(?!\/)/,"Use an internal path beginning with /");
const navigationSchema=z.array(z.object({label:z.string().min(1).max(80),labelIt:z.string().max(80),href:internalPath,order:z.number().int().nonnegative(),visible:z.boolean()})).max(20);
const footerNavigationSchema=z.array(z.object({title:z.string().min(1).max(80),titleIt:z.string().max(80),links:z.array(z.object({label:z.string().min(1).max(80),labelIt:z.string().max(80),href:internalPath})).max(20)})).max(10);
const socialSchema=z.array(z.object({label:z.string().min(1).max(80),href:z.url()})).max(12);
const chromeSchema=z.object({companyName:z.string().trim().min(1).max(100),companyLogo:internalPath,navigation:navigationSchema,headerCta:z.object({label:z.string().trim().min(1).max(80),labelIt:z.string().trim().max(80),href:internalPath}),footerLogo:internalPath,footerDescription:z.string().trim().min(10).max(600),footerDescriptionIt:z.string().trim().max(600),socialLinks:socialSchema,copyrightText:z.string().trim().min(2).max(200),copyrightTextIt:z.string().trim().max(200),footerTagline:z.string().trim().min(2).max(200),footerTaglineIt:z.string().trim().max(200),footerNavigation:footerNavigationSchema,footerCta:z.object({title:z.string().trim().min(1).max(100),titleIt:z.string().trim().max(100),description:z.string().trim().min(2).max(300),descriptionIt:z.string().trim().max(300),buttonLabel:z.string().trim().min(1).max(80),buttonLabelIt:z.string().trim().max(80),buttonHref:internalPath})});
const contactSchema=z.object({address:z.string().trim().min(2).max(300),addressIt:z.string().trim().max(300),phone:z.string().trim().min(6).max(40),email:z.email(),whatsapp:z.string().trim().min(6).max(40),callingHours:z.string().trim().min(2).max(300)});
export type ChromeActionState={status:"success"|"error";message:string}|undefined;
function lines(value:FormDataEntryValue|null){return String(value??"").split("\n").map(line=>line.trim()).filter(Boolean);}
export async function saveSiteChrome(_state:ChromeActionState,formData:FormData):Promise<ChromeActionState>{await requireAdmin();
  const navigationItalian=new Map(lines(formData.get("navigationIt")).map(line=>{const[label,href]=line.split("|").map(v=>v.trim());return[href,label];}));
  const navigation=lines(formData.get("navigation")).map((line,order)=>{const[label,href,visibility="visible"]=line.split("|").map(v=>v.trim());return{label,labelIt:navigationItalian.get(href)??"",href,order,visible:visibility.toLowerCase()!=="hidden"};});
  const footerItalian=new Map(lines(formData.get("footerNavigationIt")).map(line=>{const[group,label,href]=line.split("|").map(v=>v.trim());return[href,{group,label}];}));
  const groupMap=new Map<string,Array<{label:string;labelIt:string;href:string}>>();for(const line of lines(formData.get("footerNavigation"))){const[group,label,href]=line.split("|").map(v=>v.trim());groupMap.set(group,[...(groupMap.get(group)??[]),{label,labelIt:footerItalian.get(href)?.label??"",href}]);}
  const chrome=chromeSchema.safeParse({companyName:formData.get("companyName"),companyLogo:formData.get("companyLogo"),navigation,headerCta:{label:formData.get("headerCtaLabel"),labelIt:formData.get("headerCtaLabelIt")??"",href:formData.get("headerCtaHref")},footerLogo:formData.get("footerLogo"),footerDescription:formData.get("footerDescription"),footerDescriptionIt:formData.get("footerDescriptionIt")??"",socialLinks:lines(formData.get("socialLinks")).map(line=>{const[label,href]=line.split("|").map(v=>v.trim());return{label,href};}),copyrightText:formData.get("copyrightText"),copyrightTextIt:formData.get("copyrightTextIt")??"",footerTagline:formData.get("footerTagline"),footerTaglineIt:formData.get("footerTaglineIt")??"",footerNavigation:[...groupMap].map(([title,links])=>({title,titleIt:footerItalian.get(links[0]?.href)?.group??"",links})),footerCta:{title:formData.get("footerCtaTitle"),titleIt:formData.get("footerCtaTitleIt")??"",description:formData.get("footerCtaDescription"),descriptionIt:formData.get("footerCtaDescriptionIt")??"",buttonLabel:formData.get("footerCtaButtonLabel"),buttonLabelIt:formData.get("footerCtaButtonLabelIt")??"",buttonHref:formData.get("footerCtaButtonHref")}});
  const contact=contactSchema.safeParse({address:formData.get("address"),addressIt:formData.get("addressIt")??"",phone:formData.get("phone"),email:formData.get("email"),whatsapp:formData.get("whatsapp"),callingHours:formData.get("callingHours")});
  if(!chrome.success)return{status:"error",message:chrome.error.issues[0]?.message??"Check the header and footer fields."};if(!contact.success)return{status:"error",message:contact.error.issues[0]?.message??"Check the contact fields."};
  const batch=adminDb.batch();const timestamp=FieldValue.serverTimestamp();batch.set(adminDb.collection(SITE_CHROME_COLLECTION).doc(SITE_CHROME_DOCUMENT),{...chrome.data,updatedAt:timestamp});batch.set(adminDb.collection(CONTACT_COLLECTION).doc(CONTACT_DOCUMENT),{...contact.data,updatedAt:timestamp},{merge:true});await batch.commit();
  revalidateTag("site-chrome","max");revalidateTag("contact-content","max");revalidatePath("/","layout");revalidatePath("/contact");revalidatePath("/admin/navigation");revalidatePath("/admin/contact");return{status:"success",message:"Header and footer saved."};}
