"use client";
import { Check,ChevronRight,MapPin,Navigation } from "lucide-react";
import { useState } from "react";
import type { ServiceArea } from "@/lib/database/service-areas";
import type { Locale } from "@/lib/i18n/config";

function embedUrl(area:ServiceArea){if(area.mapsUrl.includes("output=embed")||area.mapsUrl.includes("/embed"))return area.mapsUrl;return`https://www.google.com/maps?q=${encodeURIComponent(area.areaName)}&output=embed`;}
export default function ServiceAreasExplorer({areas,locale}:{areas:ServiceArea[];locale:Locale}){
  const[selectedId,setSelectedId]=useState(areas[0]?.id??"");const selected=areas.find(area=>area.id===selectedId)??areas[0];const it=locale==="it";
  if(!selected)return<section className="mx-auto max-w-7xl px-5 py-20 text-center text-slate-500">{it?"Al momento non ci sono zone servite pubblicate.":"No service areas are currently published."}</section>;
  return <><section className="border-b border-slate-200 bg-white lg:hidden"><div className="overflow-x-auto px-5 py-4"><div className="flex min-w-max gap-3">{areas.map(area=><button key={area.id} type="button" onClick={()=>setSelectedId(area.id)} className={`inline-flex items-center gap-2 rounded-full border px-5 py-3 text-sm font-semibold transition ${selected.id===area.id?"border-blue-600 bg-blue-600 text-white":"border-slate-300 bg-white text-slate-700"}`}><MapPin className="h-4 w-4"/>{area.areaName}</button>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="grid gap-10 lg:grid-cols-[360px_1fr] lg:gap-14"><aside className="hidden lg:block">
    <p className="text-sm font-bold uppercase tracking-[0.22em] text-blue-600">{it?"Scegli una zona":"Choose an area"}</p><h2 className="mt-4 text-3xl font-bold tracking-tight">{it?"Trova Movento vicino a te":"Find Movento near you"}</h2><p className="mt-4 leading-7 text-slate-600">{it?"Seleziona una località per vedere la copertura e aprirla direttamente in Google Maps.":"Select a location to view its coverage and open the area directly in Google Maps."}</p>
    <div className="mt-8 space-y-3">{areas.map(area=><button key={area.id} type="button" onClick={()=>setSelectedId(area.id)} className={`flex w-full items-center justify-between rounded-2xl border p-5 text-left transition ${selected.id===area.id?"border-blue-600 bg-blue-50":"border-slate-200 bg-white hover:border-blue-300"}`}><span><span className="block font-bold text-slate-950">{area.areaName}</span><span className="mt-1 block text-sm text-slate-500">{area.shortDescription}</span></span><ChevronRight className={`h-5 w-5 shrink-0 ${selected.id===area.id?"text-blue-600":"text-slate-400"}`}/></button>)}</div>
  </aside><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="relative h-[310px] w-full bg-slate-100 sm:h-[420px] lg:h-[480px]"><iframe key={selected.id} src={embedUrl(selected)} title={it?`Mappa Google di ${selected.areaName}`:`Google Map showing ${selected.areaName}`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" className="absolute inset-0 h-full w-full border-0" allowFullScreen/></div><div className="p-6 sm:p-8">
    {selected.featuredImage&&(
      // eslint-disable-next-line @next/next/no-img-element -- CMS images may use any validated HTTPS host.
      <img src={selected.featuredImage} alt={selected.areaName} loading="lazy" decoding="async" className="mb-7 aspect-[16/7] w-full rounded-2xl bg-slate-100 object-cover" />
    )}
    <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div>{selected.featured&&<p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-600">{it?"Zona in evidenza":"Featured service area"}</p>}<h2 className="mt-2 text-3xl font-bold tracking-tight">{it?`Servizi di trasloco a ${selected.areaName}`:`Moving services in ${selected.areaName}`}</h2></div><a href={selected.mapsUrl} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full border border-slate-300 px-5 py-3 font-semibold text-slate-900 transition hover:border-blue-600 hover:text-blue-600"><Navigation className="h-5 w-5"/>{it?"Apri in Maps":"Open in Maps"}</a></div>
    <p className="mt-5 max-w-3xl leading-7 text-slate-600">{selected.fullDescription}</p>{selected.availabilityNotes&&<p className="mt-5 rounded-2xl bg-blue-50 p-4 text-sm font-semibold leading-6 text-blue-900">{selected.availabilityNotes}</p>}
    {selected.nearbyCities.length>0&&<div className="mt-8"><p className="font-bold text-slate-950">{it?"Zone generalmente coperte":"Areas commonly covered"}</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{selected.nearbyCities.map(location=><div key={location} className="flex min-w-0 items-center gap-2 rounded-xl bg-slate-50 px-3 py-3 text-sm font-medium text-slate-700"><Check className="h-4 w-4 shrink-0 text-blue-600"/><span className="truncate">{location}</span></div>)}</div></div>}
  </div></div></div></section></>;
}
